### ISSUE TITLE
Custom Templates

### ISSUE THREAD

**Issue by Zuescho** [omegas82128/Aikino#53]
**Is your feature request related to a problem? Please describe.**
I would like to use a different Template instead of the provided one.

**Describe the solution you'd like**
Let us chose which template should be used, maybe in the same dropdown as the simple / template selection.

**Describe alternatives you've considered**
Let us replace the template as a file in the Program Files folder.

**Additional context**
Thanks for the Program does a lot of things better than the alternatives i have found so far.

**Comment by omegas82128** [comment]
I have been thinking about this too. But I never thought about completely customizable cause of some requirements.

Still I have thought about this, and I think I can implement it. But the inputs will have to be more than just the templates image.

The user will have to provide the size of the poster within the template too. Also they need to provide the starting pixels of poster in the template, which makes it a bit more complicated. I could initially put the burden on the user and let them be responsible for the calculations. And eventually update the app to help with them. 

But honestly the easiest and simplest way would be to just integrate your template as a permanent part of the app. But if you are not comfortable with that or would just rather prefer a customizable template option, I will work on it. 

Also it's not either or. I could add your template as part of the app for the next release and then add the customizable template feature in future releases

**Comment by Zuescho** [comment]
Yeah this could lead to some problems, for now i wanted to try to just replace the template png in the jar file with my own (or better said something I found on the Internet).

For example, I would use this now https://www.deviantart.com/920r9/art/DVD-Plastic-Case-for-GIMP-106113654
but I can see how it would get problematic if I could just add any template, like for example these, which are going for a whole different style.
https://www.deviantart.com/faelpessoal/art/PSD-Template-faelpessoal-754185055

**Comment by omegas82128** [comment]
Hi, apologies for the late reply. I was sick and dealing with some personal stuff. But I had some time today and I refactored my code a bit and I have added the dvd box you want. There's still a lot of stuff left before I can make an official release, but I wanted to update you on the progress. 

Hopefully the release will be out by next weekend 

![image](https://user-images.githubusercontent.com/62013556/135711116-fca5330e-fa2b-498e-a701-6a728bbdde01.png)

**Comment by omegas82128** [comment]
Also the other templates are a bit different, but I believe I can eventually fit them into the app as well. I wrote the code keeping in mind I will add multiple templates. Still it's a lot messier than I remember, I'll clean it up and eventually improve everything else too
