### ISSUE TITLE
Aikino 2.7.7 not running (Windows 10)

### ISSUE THREAD

**Issue by Zuescho** [omegas82128/Aikino#57]
Hi, sorry to bother you again, but I'm running into some weird bug.

**Describe the bug**
I installed Aikino on another Computer where the 2.6.6 Version was running, here for some reason it does not want to start.

You just get to the Start Menu, when trying to click Settings nothing happens.

When you right-click and use the context menu "Open with Aikino" i get that it can't connect to the moviedb.

**Extra Info**
I just tried it on a Computer which never had it running, there it opens up and the Settings are working, by chance i could not locate any file where the Settings are located (any .conf or so).

I'm wondering if my settings for some reason are the problem, reinstalling/ uninstalling did not help.

**Screenshots**
![2021-10-17_02-22-20](https://user-images.githubusercontent.com/13680959/137605370-dfe42a6b-f6ac-4f09-9e01-573bdb095644.png)

**Desktop (please complete the following information):**
Windows 10
openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment Temurin-16.0.2+7 (build 16.0.2+7)
OpenJDK 64-Bit Server VM Temurin-16.0.2+7 (build 16.0.2+7, mixed mode, sharing)

**Comment by omegas82128** [comment]
Hi Zuescho, I'll look into it. But it'll be a little hard as I haven't added proper logging.

The settings are saved in windows registry, instead of config file. You can find them in registry editor in the path

HKEY_CURRENT_USER\Software\JavaSoft\Prefs\com.omegas.util./Preferences

If it's a settings issue, then deleting all the variables except current in the path above should resolve it.

Mainly you'll need to delete Icon type variable

**Comment by Zuescho** [comment]
**before**
![regedit_2021-10-17_10-40-13](https://user-images.githubusercontent.com/13680959/137619148-5879fb9f-613f-4af7-ad4e-331cfed9cebd.png)

**after**

![regedit_2021-10-17_10-44-03](https://user-images.githubusercontent.com/13680959/137619240-d5b8537e-3caa-42db-9b7a-b37ca1d1666f.png)

You are the best! That was it, after deleting the entries it worked again, I played around a bit with the settings, and it seems that because of the renaming of the ICON_TYPE from Template to Simple it maybe got confused and did not let me back into the settings.

Thanks for the quick help! Back to creating Icons

**Comment by omegas82128** [comment]
You're welcome. Also thank you for reporting this, because others will have this same problem too. I'll add a fix and update soon
